### ISSUE TITLE
Unable to open the live events generated urls in iframe

### ISSUE THREAD

**Issue by opsvibhuti** [aws-samples/amazon-chime-live-events#17]
hi , we have build the package , deployed and got the generated urls for moderator, attendee, talent and broadcaster.  We see following issues
1. We are unable to open the generated urls in iframe .
2. We put multiple talent names in the csv, but got meeting url on for one in S3.
3. Attendee dont see the live event but a video player showing " Name not playing video" , but broadcaster url working fine.

**Comment by michhyun1** [comment]
Hey there, thanks for your patience.
At this time, we only support one talent, hence the one talent in S3. Also, please don't join the meeting using the broadcaster url, only with Attendee/Moderator urls. Can you be a bit more specific about the iframe issue you are facing?

thanks

**Comment by opsvibhuti** [comment]
hi Michael , 

thanks for the update !
Its not completely clear from your reply though , let me share more details for each of the three above

1 : didnt hear back on this one
2 : No problem , we can use attendee/moderator role for talent. No big deal.
3 : " please don't join the meeting using the broadcaster url, only with Attendee/Moderator urls. " 
Let me write our screnario. We are going to have this in the Live event
S Speaker/Talent : 2
M Moderators : 3
V VIP ( who can raise hand ) : 50
A Audience ( who can just watch only ) : 700

So for S and M we shall use Moderator role , for V we shall use Attendee role and for A who watch it ( we are trying to use boradcast url ) . So please suggest what url to use for audience ?

4. Further can we any RTMP with it like MUX. ( we tried it with the videconference sample already though , but could nt find anything in it for the same yet ) .

Thanks !

**Comment by opsvibhuti** [comment]
hi any update ?

**Comment by opsvibhuti** [comment]
any update on above by anyone, most importantly iframe ?

**Comment by michhyun1** [comment]
Thanks for your patience. 

1. For using the generated URLs in an iframe, we don't support this in this demo, but we'd be more than happy to help debug any issues regarding this. You would likely need to play around with the CSP policies to get it to work.

I believe [this](https://github.com/aws-samples/amazon-chime-live-events/blob/39b1fc8115dcc52ffdac4dbb8c8d7ef57a6e32d9/src/backend/serverless/src/addResponse.js#L10) would be a good place to look

3. We only really have a moderator, talent, and audience role. The broadcaster url is not meant for an audience member to join, instead it is used to broadcast the media from the broadcast url to a RTMP endpoint URL. Don't use the broadcast URL, or you might have some issues with the live event meeting. The only URLs you should provide are the talent URL (only 1) to your talent, the moderator URLs, and attendee URLs. 

Currently there isn't a way to distinguish a regular attendee from what you are calling a VIP audience member. Any member of the audience can raise a hand, and the moderator should be able to invite an audience member to a 'waiting room' where the moderator can split off into a 1-1 meeting with the audience member to prep them before the moderator features that audience member on the live feed.

4. If you can provide more details, that would be helpful

**Comment by nicklera1** [comment]
Hi @opsvibhuti , 

I just to add a little bit more context as to what "Broadcaster" URL is and what it's used for.
As part of the LiveEvents deployment we also deploying [Transcoder](https://github.com/aws-samples/amazon-chime-live-events/tree/master/transcoding) which is basically an EC2 instance running browser where we open "Broadcaster" url and run OBD (screen capture) of the given event and then transcoding it into HLS (.m3u8) for streaming. [Check here](https://github.com/aws-samples/amazon-chime-live-events/tree/master/transcoding#options-to-startstop-transcoding) to see how you start and stop transcoder. 
In [Attendee View](https://github.com/aws-samples/amazon-chime-live-events/blob/24fb61fb0bb00d02a0ed6f3535b2d0acaaaaea72/src/components/VideoPlayer/index.tsx#L35) we use [HLS endpoint](https://github.com/aws-samples/amazon-chime-live-events/blob/24fb61fb0bb00d02a0ed6f3535b2d0acaaaaea72/src/utils/configuredURLs.ts#L44) from [Transcoder] (https://github.com/aws-samples/amazon-chime-live-events/tree/master/transcoding) and stream it to attendees. 

I assume you would like to use MUX as transcoder? if so then you would need to capture broadcaster view and feed as part of your RTMP to MUX for transcoding and then you will need to update [default HLS](https://github.com/aws-samples/amazon-chime-live-events/blob/24fb61fb0bb00d02a0ed6f3535b2d0acaaaaea72/src/utils/configuredURLs.ts#L22) endpoint to the one provided by MUX API's [HLS endpoint ](https://stream.mux.com/2OvZzkW02n42f01S8zYpgB1ZpyKUIiLjKQ.m3u8) that way attendees will able to stream content from MUX.

Thanks

**Comment by opsvibhuti** [comment]
hi Nickolay, 
hi Michael ,

We were able to fix 1 and 2 , thanks ! but still stuck on #3 and one more question on pricing. 

#3 . 
let me rewrite in simple words. How do we stream the meeting to extenal users like any external video player in a website etc to watch , like zoom give us a url to stream the webinar to any rtmp ?

---------Additional Note -------
Again in core, As per our screnario. We are going to have this in the Live event

S Speaker/Talent : 2 people ( AWS Live Event SDK role : Moderator , as we have multiple speakers and this sdk gives only one Talent option for now )
M Moderators : 3  people  ( AWS Live Event SDK role : Moderator )
V VIP ( who can raise hand ) : 50 people  ( AWS Live Event SDK role : Attendee )
A Audience ( who can just watch only ) : 700 people  ( what url we can show here to the audience which are viewer only ? If we get one live meeting url for audience , we can then hook it with MUX and put mux url in our website and can show to 700 people using this https://github.com/aws-samples/amazon-chime-meeting-broadcast-demo , but point is what is the viewers/external-broadcast url ?)

So for S and M we shall use Moderator role , for V we shall use Attendee role and for A who watch it ( we are trying to use boradcast url ) . So please suggest what url to use for audience ?
-----------------------------------

#5. for the above model , what will be the pricing , say we have above scenario and one session will run for 8 hrs. We referenced this article https://aws.amazon.com/blogs/media/frequently-asked-questions-about-the-cost-of-live-streaming/ , here it is calculating as per 5000 viewers , but in our case we are not sure viewers are attendees only or users watching the meeting . If later what is the url for them to watch only ?

**Comment by opsvibhuti** [comment]
#6. We have observed that if we run an event and if it remain idle for some time ( Can we get what time limit value is on time? ), then it stops working. Can you we keep it alive until we manually turn off medialive etc ? 

Regards !

**Comment by ericcox3** [comment]
> for the above model , what will be the pricing , say we have above scenario and one session will run for 8 hrs. We referenced this article https://aws.amazon.com/blogs/media/frequently-asked-questions-about-the-cost-of-live-streaming/ , here it is calculating as per 5000 viewers , but in our case we are not sure viewers are attendees only or users watching the meeting .

Hello opsvibhuti,
To answer your question about pricing, an "attendee", whether or not they can raise their hand, counts as a viewer of the Elemental stream.  They are not in the Chime meeting so they're not charged at the Chime rate.  The only Chime attendees in your scenario are Speaker and Moderator, and they will be charged the Chime rate ($0.0017 per attendee per minute at the time of writing this).  The rest will be charged according to the Elemental pricing you referenced.

**Comment by michhyun1** [comment]
In response to 3, we don't support this type of "public url," that can be shared with anyone as part of this demo. You should be able to use an arbitrary attendee url for multiple attendees and they should all be able to see the broadcast, but they may not be able to join the meeting.

In response to 6: There are certain features of the Chime SDK that automatically end meetings when certain criteria are met. For more information, please refer to [this article](https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html) under "A meeting automatically ends after a period of inactivity, such as the following".

Also, just as a side note - using the syntax (# 5) references another github issue. You may just use the number without a hashtag (5) to reference the fifth item.

**Comment by p-foucht** [comment]
Resolving this ticket since the initial question was answered. We'd like to keep issues and questions searchable for other developers, so if you have more questions feel free to file another ticket.
