### ISSUE TITLE
Unable to run cloudfront demo url in Iframe 

### ISSUE THREAD

**Issue by prabhupadhayay** [aws-samples/amazon-chime-live-events#18]
I want to run this demo url in Iframe and facing some issue.It is not running in iframe.although it is running fine when used externally.Attached screenshot for this too-

![Screenshot_1](https://user-images.githubusercontent.com/51395692/90890825-58c57c80-e3d8-11ea-80d0-19951a4cc592.png)

**Comment by prabhupadhayay** [comment]
I got these urls auto generated to run live events

**Comment by p-foucht** [comment]
The demo does not support rendering within an iframe. You would likely need to play around with the CSP policies to get it to work.

I believe [this](https://github.com/aws-samples/amazon-chime-live-events/blob/39b1fc8115dcc52ffdac4dbb8c8d7ef57a6e32d9/src/backend/serverless/src/addResponse.js#L10) would be a good place to look

**Comment by prabhupadhayay** [comment]
Thanks @p-foucht 
Thanks for the solution. It worked for me
