### ISSUE TITLE
Unable to deploy two or more live events demo applications(town-hall) on AWS.

### ISSUE THREAD

**Issue by prabhupadhayay** [aws-samples/amazon-chime-live-events#19]
Hi @p-foucht 
I am trying to deploy the live event sdk to host  multiple events at a time (parallel)  but I getting some errors
![Screenshot from 2020-09-04 19-02-02](https://user-images.githubusercontent.com/51395692/92245329-d8c40a00-eee1-11ea-9a36-dc218f27c78c.png)
.

**Comment by p-foucht** [comment]
Hi prabhupadhayay,

It sounds like the stack that got setup in your AWS account is in "ROLLBACK_COMPLETE" state. If you go to the Cloudformation service in AWS, it should give you more details.

If you are trying to deploy two individual instances, they need to be completely separate stacks/buckets/resources.

**Comment by prabhupadhayay** [comment]
thanks for the response @p-foucht 
I have deployed one stack(abc-broadcast stack ) by changing function name.
But I am unable to deploy the other two stacks.they are in "RollBack-Complete" state and I am not finding any solution to change my resource's name.Can You please tell me where i have to change name or resources for the same so that  i will be able to deploy whole live-event-app again.

**Comment by opsvibhuti** [comment]
hi @p-foucht , @michhyun1 , @nicklera1 

thanks for addressing the queries under this issue https://github.com/aws-samples/amazon-chime-live-events/issues/17
We are successfully run one Video Conference and One Live Event SDK model. 

We are having issues in deploying multiple instances of these though. 
"If you are trying to deploy two individual instances, they need to be completely separate stacks/buckets/resources." 
@p-foucht it make sense, but we are still unable to find where exactly are all these names/titles to be changed to run a separate instance.

Can you please share the file where these settings on resource names are ?

Regards, 
Munish S.

**Comment by prabhupadhayay** [comment]
Hi @p-foucht 
Any Update for above Issues?

**Comment by opsvibhuti** [comment]
Morning gentlemen , any update on it ? 
We are waiting to deploy the same.

**Comment by nicklera1** [comment]
Hi @opsvibhuti , @prabhupadhayay ,

As per our [readme](https://github.com/aws-samples/amazon-chime-live-events/tree/master/src/backend/serverless#cloudfront-deployment-1) your each deployment instance would need to have unique `-b` <bucket_name>  and `-s` <stack_name> when executing following command `node ./deploy.js -r us-east-1 -b live-event-deployment-bucket -s live-event-deployment-stack`. During deployment we will also deploy [Broadcast (transcoding) deployment](https://github.com/aws-samples/amazon-chime-live-events/blob/master/src/backend/serverless/deploy.js#L213) as part of the 'full stack' deployment and thats where we take an stack/bucket name from your input and append `-broadcast` as part of Broadcast stack deployment and [here](https://github.com/aws-samples/amazon-chime-live-events/blob/master/src/backend/serverless/deploy.js#L213) is the line where you find name for Broadcast stack setup.

**Comment by prabhupadhayay** [comment]
Thanks for the response @nicklera1 
Here we have successfully deployed that broadcast stack.Issue is with other remaining two.
For this Live event demo we have three stacks and we have successfully deployed one named -broadcast.we are not finding for the other two

**Comment by prabhupadhayay** [comment]
It will be very helpful if you help us to find the names/titles for the resources to be changed to run separate instances

**Comment by nicklera1** [comment]
Have you look at [this](https://github.com/aws-samples/amazon-chime-live-events/blob/master/src/backend/serverless/deploy.js#L213) might help you with naming.

**Comment by prabhupadhayay** [comment]
I have successfully deployed that broadcast-stack. But I am unable to deploy the other two remaining stacks

**Comment by nicklera1** [comment]
I see, One thing to note though, for each instance that you deploying you will need to have a Broadcast-stack deployed as well (live-events stack + broadcast stack)  You mentioned you have one stack fully working I would keep that working stack and remove (via AWS console) all mismatched/failed deployment stacks and start fresh and not try to fix deployment. One other thing as per your comment 

> I have successfully deployed that broadcast-stack. But I am unable to deploy the other two remaining stacks

You should not have to deploy "Broadcast" separately but instead deploy via `node ./deploy.js -r us-east-1 -b <unique-deployment-bucket> -s <very-unique-deployment-stack>` as running deployment separately might cause deployments issues.

**Comment by prabhupadhayay** [comment]
It was not a seperate deployment. I am using node ./deploy.js -r us-east-1 -b <unique-deployment-bucket> -s <very-unique-deployment-stack>  this for deployment

**Comment by opsvibhuti** [comment]
hi @nicklera1 , it make sense what you are suggested and we already tried that at first attempt by giving different bucket and stack name already. 

I guess its not just giving different stackname and bucket name in that command only because we have tried that already and its something more deep , somewhere may be hardcoded.

As @p-foucht mentioned as well that s, they need to be completely separate stacks/buckets/resources . we are requesting to  find where exactly are all these names/titles to be changed to run a separate instance. Can you please share the file where these settings on resource names are ?

I asked this here as well https://github.com/aws-samples/amazon-chime-live-events/issues/19#issuecomment-688066189 2 days ago.

any update on it @p-foucht ?

Thanks !

**Comment by opsvibhuti** [comment]
any update ? 
still waiting on the same to meet our goal and actually use AWS Chime in our solution than Zoom.

**Comment by nicklera1** [comment]
Hi @opsvibhuti 
 I will try to replicate the issue on my side and see what I can came-up with.

**Comment by nicklera1** [comment]
Ok, after some testing I see that there is a default values are set in [transcoding](https://github.com/aws-samples/amazon-chime-live-events/blob/master/transcoding/template.yaml#L28) package: in particular [ECSClusterName](https://github.com/aws-samples/amazon-chime-live-events/blob/master/transcoding/template.yaml#L28), [ECSContainerName](https://github.com/aws-samples/amazon-chime-live-events/blob/master/transcoding/template.yaml#L13), [EnvironmentName](https://github.com/aws-samples/amazon-chime-live-events/blob/master/transcoding/template.yaml#L57). I will make changes to template but to unblock you for now I would recommend that you change mentioned defaults to unique values with each deployment. Thanks

**Comment by nicklera1** [comment]
Hi @opsvibhuti, @prabhupadhayay. 

I have merged the fix for the issue I was able to deploy 3 LiveEvents instances under same account. 

Please test and let me know if you encounter any issues. 

Thanks
Nick

**Comment by opsvibhuti** [comment]
hi @nicklera1 , 

thanks for the same ! Prabhakar will be able to retry tomorrow morning and we shall let you know if there be any issue.

**Comment by prabhupadhayay** [comment]
hi @nicklera1 @p-foucht 

I got into issue with multi-deployments again .As I am not able to deploy more than 3 live events now.

My stack always encountered in "ROLLBACK_COMPLETE" state whenever I try to deploy my 4th (more than 3 ) live events solution.
Please get back to me with solution.
