### ISSUE TITLE
Multiple attendees using the same code causes issues

### ISSUE THREAD

**Issue by snwbrdr78** [aws-samples/amazon-chime-live-events#2]
Multiple attendees get the same attendee address and try to login.  This causes the moderator page to start having issues, as well as attendees can no longer get in, even with a new attendee address.

Expected:
Attendee with a duplicate address gets a prompt, to let them know that, “this attendee link is already in use, please reach out to your event coordinator for a new link.”  Or alternately, create a new attendee link on the fly (or from a pool) and forward this new attendee to that address to resolve the issue.

Steps to reproduce:
1. Give any two people the same attendee ID and have them both login and raise their hand.  If they never raise their hand, the problem is not exposed.

Notes:
I had one example of this issue, where the first attendee got all the way through setting up their camera and then the second attendee raised hand and overtook the first attendees place.  The UI did not ask the second attendee to setup camera, the second attendee was automatically placed in queue and the first attendee could no longer join.  This also broke the moderator view, as even when I gave both attendees new seperate attendee address (not previously used), neither could get in reliably.  It took creating a new event to get out of the issue.

Environment:
- Chrome Version 83.0.4103.61 (Official Build) (64-bit)
- MacOS Catalina Version 10.15.5 (19F96)

**Comment by snwbrdr78** [comment]
Update: Most recent release still allows for attendees with the same URL to kick each other, but the moderator experience is no longer broken from this.

**Comment by p-foucht** [comment]
There's currently no support for attendees using the same "credentials." This solution expects that the links are distributed to trusted attendees and not shared.

Breaking the moderator experience is problematic, but from your comment it seems to be working now. Feel free to re-open the issue if you have other comments.
