### ISSUE TITLE
How much time it takes to deploy in cloud?

### ISSUE THREAD

**Issue by RezowanTalukder** [aws-samples/amazon-chime-live-events#28]
I have run this command `node ./deploy.js -r us-east-1 -b live-event-deployment-bucket -s live-event-deployment-stack
`  and its been 2 hours, still showing `executing sam [deploy............] ` I don't get it if its running or stuck somewhere. Can anyone tell me how much time it takes to deploy in serverless cloud ?

**Comment by michhyun1** [comment]
@RezowanTalukder it should not take that long, it should take a few minutes but is there no error being thrown?

**Comment by RezowanTalukder** [comment]
Thanks it doesn't take long, there ware some errors.
