### ISSUE TITLE
Template error: Fn::Select cannot select nonexistent value at index 1

### ISSUE THREAD

**Issue by msgoo7** [aws-samples/amazon-chime-live-events#43]
Hi Team, 

I am getting the below 2 errors, please can anyone help. 
while running command:- 
node ./deploy.js -r us-east-1 -b new-test-deployment-bucket -s live-event-stack-new-test

Template error: Fn::Select cannot select nonexistent value at index 1

The following resource(s) failed to create: [PublicSubnet2, EC2InstanceProfile, BroadcastLambdaFunction, PublicRouteTable]. Rollback requested by user.

**Comment by michhyun1** [comment]
Hi @msgoo7, can you confirm your OS and node version?

**Comment by msgoo7** [comment]
Hi @michhyun1 , thanks for you response. 
It was some VPC issue. Fixed now..
