### ISSUE TITLE
Attendee Video not rendering

### ISSUE THREAD

**Issue by vijayamin83** [aws-samples/amazon-chime-live-events#48]
When I broadcast the URL with testing the 'broadcast-lambda' function, it does not rendering into the Attendee view.

FYI, I am broadcasting the URL, which I got from the JSON file which is created in S3 bucket. Am I doing the wrong?

**Comment by michhyun1** [comment]
@vijayamin83 yes that is the correct URL to broadcast. What did you use for the rtmp endpoint? 

One thing to check is this - once you join the moderator's url and join the meeting, turn on your video and go 'live'. 

Do you notice the broadcaster attendee show up in your roster on the moderator view?

Also, please send me a screenshot of the console in the attendee view. Thanks

**Comment by vijayamin83** [comment]
@michhyun1 

Yes I have tried with the moderator view also with turning ON and going "Live". 

I am not seeing the Broadcaster user in the moderator view. And I think that is the issue.

See the screen shots.

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/468540/121858934-c1d60200-cd14-11eb-9c01-9cfa2ee01165.png">
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/468540/121858973-cd292d80-cd14-11eb-8a2d-d51466aa0dd3.png">
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/468540/121859345-37da6900-cd15-11eb-954a-05a3ac09473d.png">

**Comment by michhyun1** [comment]
![image](https://user-images.githubusercontent.com/54328451/122119197-c1556e00-cddd-11eb-9d52-cf14f14ff830.png)

Okay, just to double check - these are the steps that I took:

1. Check out commit https://github.com/aws-samples/amazon-chime-live-events/commit/30c8f9e3ad66825a7088e2f4843cebdf33c51ca4
2. Create the custom resources using CSV files for attendee, moderator, and talent
3. Joined the provided attendee and moderator app with the generated URLs and access keys (moderator only)
4. Verify that there is no broadcaster showing in the roster of the moderator
5. Start the mediaLive channel, the channel specified by the CloudFormation output: MediaLiveChannelId
6. Run a test against the transcoding lambda with the following object:
```
{
  "action": "start",
  "meetingURL": "[the broadcast url that was generated in step 2]",
  "rtmpEndpoint": "[from the cloudformation outputs: MediaLivePrimaryEndpoint]"
}
```

If you've followed these steps, then you should see the screenshot above. The broadcast lambda should allow the broadcaster to join the meeting (do not open the broadcaster URL yourself). Then, the attendees should now see the broadcast. Make sure that the moderator's video is live.

**Comment by tindevelopers** [comment]
Hello @michhyun1 

I have checked out the previous version. Deleted the existing stacks and setup and followed the same steps are you mentioned above. But still I am not able to get the broadcaster in the moderator.

Also, how I can debug the EC2 for the broadcaster?

**Comment by michhyun1** [comment]
I've been able to setup 5 different live events stacks where the video works as expected. Perhaps you can refer to the steps noted in this issue: https://github.com/aws-samples/amazon-chime-live-events/issues/49

**Comment by vijayamin83** [comment]
Today, I have tried at least 3 times with fresh setup and mentioned commit version. but still Getting the error.

<img width="949" alt="image" src="https://user-images.githubusercontent.com/468540/122640708-9f7e2300-d11e-11eb-873c-b69b7aed9975.png">

here, I am sure that there is something wrong with ECS task only. Is there any way that I can debug that?

**Comment by vijayamin83** [comment]
I am getting the following error with the ECS tasks log:


Status reason | CannotPullContainerError: Error response from daemon: manifest for XXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/chime-liveevent-stk35-broadcast:latest not found: manifest unknown: Requested image not found

**Comment by michhyun1** [comment]
@vijayamin83 can you double check that the cloudformation stack has no errors when you deployed the live events stack? Thanks

**Comment by vijayamin83** [comment]
@michhyun1 No It does not have any issue in the Cloudformation.

While digging into the bug, I have found that, If I run the push commands on the ECR repository, then broadcasting video work for me. But I have to do manually from the AWS ECR Consol. I think this should be managed from the deploy script only?

**Comment by michhyun1** [comment]
@vijayamin83, we should upload the image to the ECR repo automatically when you start the transcoding lambda. You can see in our README [here](https://github.com/aws-samples/amazon-chime-live-events/blob/master/transcoding/README.md#whats-in-behind) that we explain that the ECR image should be uploaded in the deploy script. Can you try to use the '-n' option when you call deploy script? [Here is an example](https://github.com/aws-samples/amazon-chime-live-events/tree/master/transcoding#how-to-run)

**Comment by michhyun1** [comment]
ah - I think I might know why. You have to have a docker instance running. That's probably why its not being uploaded to ECR. Please have a docker instance running locally and try again. Thanks!

**Comment by michhyun1** [comment]
@vijayamin83 Has this resolved your issue? If so, please feel free to close the issue.

**Comment by vijayamin83** [comment]
yes, it's working
