### ISSUE TITLE
deployment-stack failed to create

### ISSUE THREAD

**Issue by erickvasilev** [aws-samples/amazon-chime-live-events#5]
Error shown during the deployment-stack creation in cloudformation:

> The following resource(s) failed to create: [LiveEventsKmsKey, HandRaiseSendMessagePermission, MessagingSendMessagePermission, HandRaiseAuthorizePermission, HandRaiseOnDisconnectPermission, LiveEventCloudFrontDistribution, HandRaiseConnectRoute, HandRaiseOnConnectPermission, ChimeMeetingsAccessPolicy]. . Rollback requested by user.

![image](https://user-images.githubusercontent.com/18327978/87237530-f1f09300-c429-11ea-8fa1-8ed8c166b8cb.png)

The SAM has AdministratorAccess policy. Not sure why this is happened. 

Thanks

**Comment by codeslinger** [comment]
Can you post a screenshot of the first error that happened during creation? That is usually the cause of the rollback and would better help us understand what is going wrong. Thanks.

**Comment by erickvasilev** [comment]
Hi,

It start fail on SiteDeploymentLayer

![image](https://user-images.githubusercontent.com/18327978/87427044-c5e43600-c612-11ea-9e10-4a863d002bea.png)

In Terminal, it stopped on this step:

![image](https://user-images.githubusercontent.com/18327978/87427235-0e9bef00-c613-11ea-8467-68fd72459a88.png)

Thanks

**Comment by erickvasilev** [comment]
**SOLVED**

I learn that we need a unique deployment stack name, I'm using similar deployment stack name in the tutorial :

`-s live-event-deployment-stack`

it will try to create an exist S3 bucket name.

![image](https://user-images.githubusercontent.com/18327978/87430637-14e09a00-c618-11ea-95eb-c536c248d7c1.png)

Another things is the region, (currently) the deployment stack and S3 bucket must be in the us-east-1, I'm trying to deploy in ap-southeast-1 and it fail.

![image](https://user-images.githubusercontent.com/18327978/87431896-dc41c000-c619-11ea-8582-c06ccd9ef135.png)
