### ISSUE TITLE
Region input is ignored in some resource creation 

### ISSUE THREAD

**Issue by revilwang** [aws-samples/amazon-chime-live-events#51]
I run the `deploy.js` file as the following:

```sh
node deploy.js -r ap-northeast-1 -b chime-deployment-demo-bucket -s chime-demo-stack
```

However, not everything is created inside the region. The `chime-demo-stack-broadcast` CloudFormation stack and `chime-deployment-demo-bucket-broadcast` bucket are created in us-east-1, which leads the following `chime-demo-stack` in ap-northeast-1 region failed to find dependent resources: 

> Resource handler returned message: "Invalid request provided: The function must be in region 'us-east-1'. ARN: arn:aws:lambda:ap-northeast-1:_my-user-id_:function:chime-demo-stack-LiveEventAddResponse-fYQf3MsJkfFW:1 (Service: CloudFront, Status Code: 400, Request ID: xxx, Extended Request ID: null)" (RequestToken: xxx, HandlerErrorCode: InvalidRequest)

**Comment by michhyun1** [comment]
@revilwang thanks for bringing this to our attention. At this time, we suggest using the default 'us-east-1' region so that you won't run into this issue. We've noted this issue and we'll try to get back to this as soon as we can. Thanks
