### ISSUE TITLE
Separate Live and Holding room audio?

### ISSUE THREAD

**Issue by paul365** [aws-samples/amazon-chime-live-events#52]
Hi guys! Can you guide me on how to separate live and holding room audio? Right now when you unmute from the holding room you will be heard in the live broadcast. We would like to have moderators and attendees able to speak with each other in the holding room before pushing them live. I know this would require an additional chime meeting to run but how to implement it? Thanks!

**Comment by michhyun1** [comment]
Yes, that is the point of the holding room - a moderator should be able to "bring in" an attendee to a holding room in order to vet them before they are promoted to the live event. https://aws.amazon.com/blogs/opensource/how-to-deploy-a-live-events-solution-built-with-the-amazon-chime-sdk/

Can you elaborate more on "Right now when you unmute from the holding room you will be heard in the live broadcast." Which app are you using and what are the repro steps? Thanks

**Comment by michhyun1** [comment]
There are three routes within the attendees app - https://github.com/aws-samples/amazon-chime-live-events/blob/master/src/components/attendee/Root.tsx#L37-L53

One is for when the attendee is just viewing, one is for the dressing room view, and the other is the meeting view.

**Comment by paul365** [comment]
Thanks for the response @michhyun1
Yup, but once they are vetted in and already in the holding room but not yet live. When you unmute the attendee they can be heard also on the live event (not having to promote them to live yet).

Using this repo and using the Moderator and Attendee views. What we want to achieve is to be able to talk to people inside the holding room without it being heard in the live event. Just like the 1:1 meeting but for the whole holding room (multiple people between attendees and moderators).

**Comment by michhyun1** [comment]
@paul365 are you broadcasting the Broadcast URL in the transcoder lambda test function? That seems odd that you'd hear the attendee audio while in the holding room because there should be separate meetings for each moderator/attendee 1:1.

**Comment by paul365** [comment]
@michhyun1 We don't hear the 1:1 on the live event. But would also want the holding room audio to be not heard from live event. So that attendees and moderators in the holding room would be able to speak to each other while not yet promoted to live.

**Comment by paul365** [comment]
Closing this. We've found how to do it. Thanks!
