### ISSUE TITLE
Architecture image attempting to load from corp.amazon.com

### ISSUE THREAD

**Issue by caseymrm** [aws-samples/amazon-chime-live-events#6]
The image at the bottom here: https://github.com/aws-samples/amazon-chime-live-events/tree/master/transcoding

Is broken for those of us not within Amazon.

```
## Broadcast/Recording General Architecture
![architecture](https://drive-render.corp.amazon.com/view/ziyiz@/Recording_Broadcast.png)
```

**Comment by caseymrm** [comment]
@ziyiz-amzn looks like you might own this image?

**Comment by ziyiz-amzn** [comment]
> @ziyiz-amzn looks like you might own this image?

Yep, I authored the README file in code.amazon.com, it was copied without changing the link. Will update.

**Comment by ziyiz-amzn** [comment]
Updated. Closing this issue.
