### ISSUE TITLE
How to Run Multiple Broadcasting task in Same instance

### ISSUE THREAD

**Issue by AnkurSavaliya** [aws-samples/amazon-chime-live-events#62]
Hi All,

I am want to run multiple tasks for broadcasting, then I got Resource Error.
How can we run Multiple Broadcasting task at time.

**Comment by michhyun1** [comment]
@AnkurSavaliya It would help if you could give more context as to what you are trying to do. Where is the resource error coming from and what did you change to get that error?

**Comment by jing-chen1** [comment]
Closing this issue, feel free to reopen it if you still have problems
