### ISSUE TITLE
Amazon Chime Url Issue in IOS device Responsive + Black Screen Video + Promoting attendee to live

### ISSUE THREAD

**Issue by preeti-jaswal** [aws-samples/amazon-chime-live-events#65]
Hi ,
I run the moderator ,attendees and talent url on the web after the deployment ,everything seems to be working fine on it .
But when I run those urls on the mobile(Android /IOS) platforms in my react-native app (inside react-native-webview).I am getting issues for responsiveness.Design seems to be broken on the mobile platform.

Any help would be appreciated
Thanks in advance.

**Comment by nainkunal933** [comment]
Hi @preeti-jaswal,

Thank you for opening this issue. Can you please provide some more details on what kind of responsiveness issues you are running into? 

For this, a screenshot of the broken design will be helpful.
> Design seems to be broken on the mobile platform.

**Comment by preeti-jaswal** [comment]
> Hi @preeti-jaswal,
> 
> Thank you for opening this issue. Can you please provide some more details on what kind of responsiveness issues you are running into?
> 
> For this, a screenshot of the broken design will be helpful.
> 
> > Design seems to be broken on the mobile platform.

Hello @nainkunal933,
Though I have run the the Moderator and Attendee Url on Mac ,Linux and android Chrome Browser and all are working fine in it but when I run the same Url on IOS inside chrome browser it 
Shows “You’re using an unsupported browser.We recommend using Firefox or chrome.”,
And when run on the safari browser it shows the Video get stuck and it starts showing black screen and when we add Attendee Video comes at the end of the page and not on inside the holding rooms section and when we transfer attendee to live, the moderator Screen gets reset to “Getting Ready” Screen.

Also if we run Attendee on Android or Web and Moderator on IOS We are able to see Moderator Video on Attendee`s(Android) end but black screen on moderator`s(IOS) end


![IMG_0675](https://user-images.githubusercontent.com/74595095/139387219-5335408c-6f8b-43b1-a393-f58091060ba2.PNG)

![IMG_0674](https://user-images.githubusercontent.com/74595095/139387260-76cf1ebd-37bc-4d46-83b4-d5a7414b9d9d.PNG)

![IMG_0673](https://user-images.githubusercontent.com/74595095/139387518-deafac37-258b-4393-8e57-86bbf1a7be93.PNG)

![IMG_0671](https://user-images.githubusercontent.com/74595095/139387545-610169c0-bfdd-4e43-aa2c-79086e2c7c44.PNG)

![IMG_0672](https://user-images.githubusercontent.com/74595095/139387571-29c191d4-8c04-4c6f-a79e-942c745e8b32.PNG)

![1f7ff2d3-4819-466a-bd0d-f6f3d543a739](https://user-images.githubusercontent.com/74595095/139387665-481ad988-5d93-4744-9aff-8e4e0684558a.jpg)

**Comment by nainkunal933** [comment]
Hi @preeti-jaswal,

I have looked into the issue and I am sorry the demo does not render well on mobile. It wasn't originally designed to render well on mobile - however we welcome contributions if you wish to engage and improve it
