### ISSUE TITLE
The project does not stand up even though I run it according to the project instructions.

### ISSUE THREAD

**Issue by mustafasavul** [aws-samples/amazon-chime-live-events#68]
Hello, when I wanted to stand up the sample project, I made the installations as in the README.md file. However, it didn't work, so I did a run through the Ubuntu terminal and this time it gave the following error.
![image](https://user-images.githubusercontent.com/19707331/147747653-7dad03d8-3bb1-4603-9ef9-008d84e0c509.png)

I installed all npm packages. However, this error still does not go away. Do you have a suggestion or solution?

Node.JS Version: v16.13.1
NPM Version: 8.3.0
Ubuntu Terminal Latest version
OS: Windows 10

**Comment by codeslinger** [comment]
It doesn't look like we have a symbol named `heartbeatInterval` in this repository. Is it possible that this is related to your specific setup somehow?

**Comment by mustafasavul** [comment]
> It doesn't look like we have a symbol named `heartbeatInterval` in this repository. Is it possible that this is related to your specific setup somehow?

I got the same error when I pulled the repo directly and followed the instructions, except for the custom installation. There were some suggestions about "heartbeatInterval" in a Chinese forum, I applied them too, but I was not successful. Did you pull it to your computer and test it?

**Comment by michhyun1** [comment]
@mustafasavul Can you please show me the error when you build it? I assure you, you don't need the heartbeatInterval, not sure where you got that from. Thanks

**Comment by mustafasavul** [comment]
Thank you the project normally
when i install it on windows package cannot access node_modules in json. I researched this and they suggested I run it with ubuntu terminal. After downloading and installing Ubuntu from the store, I added node-js to it and called the latest version. Then the project stood up without fail. It was a really weird problem and solution :D
